######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 28 16:47:04 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
